export const strings = {
  searchCity: 'Search city',
  sorryNoCityFOund: 'Sorry no city found',
  dailyForeCast: 'Daily forecast',
  hourlyForecast: 'Hourly forecast',
  forecastDays: 'days forecast',
  degree: ' °',
  degreeC: ' °C',
  kmph: 'kmph',
  percentage: ' %',
  feelsLike: 'feels like',
  oops: 'Ooops!!!',
  prepChances: 'Prep. Prob',
  noCitySelected: 'No city is selected. Please select the City',
  selectCity: 'Select City',
};

export const appConstants = {
  sunny: 'Sunny',
  cloudy: 'Cloudy',
  partlyCloudy: 'Partly cloudy',
  clear: 'Clear',
  heavyRain: 'Heavy rain',
  heavyRainAtTimes: 'Heavy rain at times',
  heavySnow: 'Heavy snow',
  lightRain: 'Light rain',
  lightRainShower: 'Light rain shower',
  mist: 'Mist',
  moderateHeavyFreezingRain: 'Moderate or heavy freezing rain',
  moderateHeavyFreezingShower: 'Moderate or heavy rain shower',
  moderateHeavyRainWithThunder: 'Moderate or heavy rain with thunder',
  moderateHeavySnowShower: 'Moderate or heavy snow showers',
  moderateRain: 'Moderate rain',
  moderateRainTimes: 'Moderate rain at times',
  weather: 'weather',
  CityName: 'CityName',
};
